config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dream Texts</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="collapse navbar-collapse navbar-menubuilder">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
        </div>
      </div>
    </div>
  

    <%= yield %>

    <footer>
      &copy; 2019 MooingLlama
    </footer>
  </body>
</html>

app/views/simple_pages/about.html.erb
<h1>About The Mooing Llama</h1>
<p>Find me in app/views/simple_pages/about.html.erb</p>

app/views/simple_pages/contact.html.erb
<h1>Contact Me</h1>
<p>Find me in app/views/simple_pages/contact.html.erb</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Dream Texts</h1>
<h2>Dream Texts from your Secret Admirer</h2>
<%= image_tag("SpikeSpiegel.jpg",class: "img-responsive") %>
<p>Meet Spike!<br>He's funny and witty</p>